//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class admin
    {
        public int admin_id { get; set; }
        public string admin_name { get; set; }
        public Nullable<long> admin_contact_no { get; set; }
        public string admin_email { get; set; }
        public string admin_password { get; set; }
        public string admin_address { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
