//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public customer()
        {
            this.customer_order = new HashSet<customer_order>();
        }

        public string LoginErrorMessage { get; set; }
        public int cus_id { get; set; }
        public string cus_name { get; set; }
        public Nullable<int> cus_card_no { get; set; }
        public Nullable<int> cus_package { get; set; }
        public Nullable<long> cus_contact_no { get; set; }
        public string cus_email { get; set; }
        public string cus_password { get; set; }
        public string cus_address { get; set; }
        public Nullable<System.DateTime> cus_ssd { get; set; }
        public Nullable<System.DateTime> cus_sed { get; set; }
        public Nullable<long> cus_totalypaid { get; set; }
        public Nullable<int> cus_payment_left { get; set; }
    
        public virtual package package { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_order> customer_order { get; set; }
    }
}
