//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_card_number
    {
        public int ccn_id { get; set; }
        public int givenQuantity { get; set; }
        public Nullable<long> ccn_numbers { get; set; }
    }
}
