//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_order
    {
        public int cusOrder_id { get; set; }
        public string cusOrder_productName { get; set; }
        public Nullable<int> cusOrder_customer { get; set; }
        public Nullable<int> cusOrder_product { get; set; }
        public Nullable<int> cusOrder_quantity { get; set; }
        public Nullable<int> cusOrder_amount { get; set; }
        public Nullable<System.DateTime> cusOrder_date { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual product product { get; set; }
    }
}
