//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dealer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dealer()
        {
            this.dealer_order = new HashSet<dealer_order>();
        }

        public string LoginErrorMessage { get; set; }
        public int dealer_id { get; set; }
        public string dealer_name { get; set; }
        public Nullable<long> dealer_contact_no { get; set; }
        public string dealer_email { get; set; }
        public string dealer_password { get; set; }
        public string dealer_address { get; set; }
        public Nullable<long> dealer_totalypaid { get; set; }
        public Nullable<int> dealer_payment_left { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealer_order> dealer_order { get; set; }
    }
}
