//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dealer_order
    {
        public int dealOrder_id { get; set; }
        public string dealOrder_Name { get; set; }
        public Nullable<int> dealOrder_dealer { get; set; }
        public Nullable<int> dealOrder_product { get; set; }
        public Nullable<int> dealOrder_quantity { get; set; }
        public Nullable<int> dealOrder_amount { get; set; }
        public Nullable<System.DateTime> dealOrder_date { get; set; }
    
        public virtual dealer dealer { get; set; }
        public virtual product product { get; set; }
    }
}
