//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class feedback
    {
        public int fb_id { get; set; }
        public string fb_name { get; set; }
        public string fb_mobile_ { get; set; }
        public string fb_email { get; set; }
        public string fb_message { get; set; }
    }
}
