//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rdthEntities : DbContext
    {
        public rdthEntities()
            : base("name=rdthEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<package> packages { get; set; }
        public virtual DbSet<customer> customers { get; set; }
        public virtual DbSet<dealer> dealers { get; set; }
        public virtual DbSet<product> products { get; set; }
        public virtual DbSet<admin> admins { get; set; }
        public virtual DbSet<customer_order> customer_order { get; set; }
        public virtual DbSet<dealer_order> dealer_order { get; set; }
        public virtual DbSet<faq> faqs { get; set; }
        public virtual DbSet<Movy> Movies { get; set; }
        public virtual DbSet<scratch_card> scratch_card { get; set; }
        public virtual DbSet<feedback> feedbacks { get; set; }
        public virtual DbSet<customer_card_number> customer_card_number { get; set; }
        public virtual DbSet<package_change_request> package_change_request { get; set; }
    }
}
