//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class Movy
    {
        public int movie_id { get; set; }
        public string movie_name { get; set; }
        public string movie_image { get; set; }
        public string movie_language { get; set; }
        public string movie_availablity { get; set; }
        public Nullable<int> movie_channelNo { get; set; }
        public string movie_duration { get; set; }
        public string movie_timing1 { get; set; }
        public string movie_timing2 { get; set; }
        public Nullable<int> movie_charges { get; set; }
        public HttpPostedFileBase MovieImage { get; set; }
    }
}
