//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_change_request
    {
        public int pcr_id { get; set; }
        public Nullable<int> pcr_packId { get; set; }
        public string pcr_packName { get; set; }
        public Nullable<int> pcr_packCharges { get; set; }
        public Nullable<int> pcr_cusId { get; set; }
        public string pcr_cusName { get; set; }
        public Nullable<long> pcr_cusCardNo { get; set; }
    }
}
