//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web;
    
    public partial class product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public product()
        {
            this.customer_order = new HashSet<customer_order>();
            this.dealer_order = new HashSet<dealer_order>();
        }
    
        public int product_id { get; set; }
        public string product_name { get; set; }
        public string product_details { get; set; }
        public string product_img { get; set; }
        public HttpPostedFileBase ImageFile { get; set; }
        public Nullable<int> product_charges { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<customer_order> customer_order { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dealer_order> dealer_order { get; set; }
    }
}
