//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace R_DTH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class scratch_card
    {
        public long card_number { get; set; }
        public Nullable<int> card_package { get; set; }
        public Nullable<int> card_charges { get; set; }
        public string card_status { get; set; }
        public int customerId { get; set; }
        public int card_check { get; set; }

        public virtual package package { get; set; }
        public string LoginErrorMessage { get; internal set; }
    }
}
